[package]
name = "yourname/mygame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TopbarPlus = "1foreverhd/topbarplus@3.4.0"
ProfileService = "brittonfischer/profileservice@2.1.5"
Knit = "sleitnick/knit@1.6.3"
Promise = "evaera/promise@4.0.0"
GoodSignal = "stravant/goodsignal@0.2.0"
TestEZ = "roblox/testez@0.4.1"
Fusion = "elttob/fusion@0.3.0"
OnyxUI = "imavafe/onyx-ui@0.4.2"
  