name: CI

on:
  push:
  pull_request:

jobs:
  lint-format-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Install tools
        run: aftman install

      - name: Format check (StyLua)
        run: stylua --check src

      - name: Lint (Selene)
        run: selene src

      - name: Rojo build
        run: |
          mkdir -p build
          rojo build default.project.json -o build/MyGame.rbxlx
